version: '2'
services:

  mysql:
    build: ./mysql
    ports:
     - "33066:3306"
    env_file: ./.env
    volumes:
     - ../logs/mysql:/var/log
     - ../data/database:/var/lib/mysql
     - ../backups/database:/backups

  nginx:
    build: ./nginx
    ports:
      - "8010:80"
      - "8011:81"
      - "8012:82"
    volumes:
     - ../logs/nginx:/var/log
     - ../api-client-libraries:/var/www/api-client-libraries
     - ../domain:/var/www/domain
     - ../frontend:/var/www/frontend
     - ../lumen-api:/var/www/lumen-api
     - ../lumen-auth:/var/www/lumen-auth
     - ../templates:/var/www/templates

  php-api:
    build: ./php-api
    ports:
      - "9000:9000"
    env_file: ./.env
    volumes:
     - ../logs/php:/var/log
     - ../domain:/var/www/domain
     - ../lumen-api:/var/www/lumen-api

  php-auth:
    build: ./php-auth
    ports:
      - "9001:9000"
    env_file: ./.env
    volumes:
     - ../logs/php:/var/log
     - ../domain:/var/www/domain
     - ../lumen-auth:/var/www/lumen-auth
     - ../templates:/var/www/templates
