version: '2'
services:

  mysql:
    build: ./mysql
    ports:
     - "33066:3306"
    env_file: ./.env
    volumes:
     - ../data/logs/mysql:/var/log
     - ../data/database:/var/lib/mysql

  nginx:
    build: ./nginx
    ports:
      - "8010:80"
      - "8011:81"
    volumes:
     - ../data/logs/nginx:/var/log
     - ../api-client-libraries:/var/www/api-client-libraries
     - ../domain:/var/www/domain
     - ../lumen-auth:/var/www/lumen-auth
     - ../templates:/var/www/templates

  php:
    build: ./php
    ports:
      - "9000:9000"
    env_file: ./.env
    volumes:
     - ../data/logs/php:/var/log
     - ../domain:/var/www/domain
     - ../lumen-auth:/var/www/lumen-auth
     - ../templates:/var/www/templates
